name: Release to PyPI

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
    paths:
      - 'pyproject.toml'

permissions:
  id-token: write  # Required for OIDC authentication
  contents: write


jobs:
  release:
    name: 🎯 Create Release & Publish to PyPI
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Olen'  # Make sure this is not a fork

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Requried to check if a tag exists already

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 🎭 Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: 🏗️ Install project
        run: poetry install

      - name: 🔍 Extract version from Poetry
        id: get_version
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "🔢 Extracted version: $VERSION"

      - name: 🔍 Check if Git tag exists
        id: check_tag
        run: |
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "⚠️ Tag v${VERSION} already exists. Skipping release!"
            exit 1
          fi

      - name: "🗝️ Get previous release version"
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"

      - name: "🏷️ Create new tag"
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ env.VERSION }}"
          tag_exists_error: false
          message: "✅ Tag Version v${{ env.VERSION }} created"

      - name: "🗒️ Generate release changelog"
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          sinceTag: ${{ steps.last_release.outputs.tag_name }}
          headerLabel: "# Notable changes since ${{ steps.last_release.outputs.tag_name }}"
          stripGeneratorNotice: true

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}
          name: 🎉 Release v${{ env.VERSION }}
          body: "${{ steps.changelog.outputs.changelog }}"
          draft: false
          prerelease: false

      - name: 🏗️ Build package with Poetry
        run: poetry build

      - name: 🚀 Publish to PyPI with OpenID
        uses: pypa/gh-action-pypi-publish@release/v1

